### PR TITLE
clean up

### PR DESCRIPTION
**Pull request by orvitpng**
This pull request includes numerous changes, none of them affecting the binary output. I'll explain them because some of them may be questionable:

- 5ec4f35c966d280079bb3392aacef90916b55953: there was a missing space which pissed me off enough to fix it.
- 142b3cb2295d5507da1ce91ddf2bc993cf8b6123: remove redundant ignores. some items should be in a local ignore, and some have no reason to be there.
- 8fb94c0dcf19966f8479cdbeb53b5cfe2fe510a0: license looks better as an MD file, even if not in markdown. also changed copyright because multiple contributors.
- 29f14ab6e693a667b7df7846c7b0a9034e1908bb: move the config example to a file without spaces. generally not a good idea to include a space in a file name, especially for a cross-platform project.
- fa0148fbe1a3ae3eb344d3fe2cfa8b2389e68da9: files that should've been ignored or non-existent in the first place were removed.

### CODE REVIEW

**Comment by orvitpng** [comment]
@Cormanz reverted

**Comment by Cormanz** [comment]
I'm almost ready to merge, but you should remove the old `LICENSE` now that you added `LICENSE.md`.

**Comment by orvitpng** [comment]
@Cormanz im really intelligent i swear

**Comment by Cormanz** [comment]
LGTM

**Pull request merged**
